version: '3.8'

services:
  frontend:
      build: 
        context: ./frontend
      container_name: carrot_market_frontend
      volumes:
        - ./frontend/app:/app
      ports:
        - "4000:4000"
        - "5555:5555"
      networks:
        - carrot

networks:
  carrot:
    name: carrot
    driver: bridge